{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wukong.credentialsSecret" . }}
  labels:
    {{- include "wukong.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.security.mysqlRootPassword | quote }}
  redis-password: {{ .Values.security.redisPassword | quote }}
{{- end }}
